// react/src/App.jsx
export default function App() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gray-50 text-gray-900">
      <h1 className="text-3xl font-bold">React Interview Starter</h1>
      <p className="text-gray-600">
        Edit <code className="rounded bg-gray-200 px-1.5 py-0.5">src/App.jsx</code> to get started.
      </p>
    </main>
  );
}

// vue/src/App.vue
<script setup></script>

<template>
  <main
    class="flex min-h-screen flex-col items-center justify-center gap-4 bg-gray-50 text-gray-900"
  >
    <h1 class="text-3xl font-bold">Vue Interview Starter</h1>
    <p class="text-gray-600">
      Edit <code class="rounded bg-gray-200 px-1.5 py-0.5">src/App.vue</code> to get started.
    </p>
  </main>
</template>
